XTribe.Web/Controllers/LandingController.cs
using System;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using Elmah;

namespace SampleMembershipSite.Controllers {
	public class LandingController : BaseController
	{
        public ActionResult Index() {
            return View();
        }

        public JsonResult AddContact(string emailAddress, string accessToken) {
            var smtp = new SmtpClient {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential("www@xtribe.co", "MailServer01!")
            };

            string body = null;

            if (!string.IsNullOrEmpty(accessToken)) {
                var facebook = new Facebook.FacebookClient(accessToken);
                dynamic asd = facebook.Get("me");
                emailAddress = asd.email;
            }
            try {
                using (var message = new MailMessage("invites@xtribe.co", "alex@xtribe.co") {
                    Subject = "New Contact",
                    Body = "A user with the email address " + emailAddress + " requested an invite"
                }) {
                    smtp.Send(message);
                }
            } catch (Exception ex) {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }

            try {

                using (var message = new MailMessage("invites@xtribe.co", emailAddress) {
                    Subject = "Thanks for your Interest",
                    Body = "Hi there!\r\nOur services is nearing the completion of our private beta which means we will soon be opening up invites to the general public. We will notify you when this exciting new service goes live!\r\n"
                }) {
                    smtp.Send(message);
                }
            } catch (Exception ex) {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }

            return new JsonResult() {
                Data = new {
                    isOK = true
                }
            };
        }
    }
}

XTribe.Web/Controllers/ProfileController.cs
using System.Web.Mvc;
using Common.Data;
using SampleMembershipSite.ViewModels;

namespace SampleMembershipSite.Controllers
{
    [Authorize]
	public class ProfileController : BaseController
    {
        private IProfileRepository _profileRepository;

        public ProfileController()
            : this(new DummyProfileRepository())
        {

        }

        public ProfileController(IProfileRepository profileRepository)
        {
            _profileRepository = profileRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Wall()
        {
            var userprofile = _profileRepository.GetProfileByUserName(User.Identity.Name);

            return View(new ProfileViewModel(userprofile));
        }
    }
}

XTribe.Web/Controllers/SnowController.cs
using System.Web.Mvc;
using SampleMembershipSite.ViewModels;

namespace SampleMembershipSite.Controllers
{
	public class SnowController : BaseController
	{
		//
		// GET: /Snow/

		public ActionResult Index()
		{
			return View( new SnowHomepageViewModel() );
		}

		public ViewResult Maps()
		{
			return View();
		}
	}

	public class DisplayUnit
	{
		public string ImageURL { get; set; }
		public string HomepageImageURL
		{
			get { return ImageURL + "?height=300&width=300&mode=crop"; }
		}
		public string Name { get; set; }
	}
}

XTribe.Web/Views/Shared/_Landing.cshtml
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Landing.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Jockey+One' rel='stylesheet' type='text/css'>
    <script src="@Url.Content("~/Scripts/vendor/jquery-1.8.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/vendor/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/underscore.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/backbone.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/xtribe.landing.js")" type="text/javascript"></script>
	<script type="text/javascript">

		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-32354245-1']);
		_gaq.push(['_setDomainName', 'xtribe.co']);
		_gaq.push(['_trackPageview']);

		(function () {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

</script>
</head>
<body>
    <div id="fb-root">
    </div>
    <div class="container">
        <section id="main">
            @RenderBody()
        </section>
    </div>
</body>
</html>

XTribe.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	<link href="@Url.Content( "~/Content/Site.css" )" rel="stylesheet" type="text/css" />
	<script src="@Url.Content( "~/Scripts/jquery-1.7.2.min.js" )" type="text/javascript"></script>
	<script src="@Url.Content( "~/Scripts/modernizr-2.5.3.js" )" type="text/javascript"></script
	
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32354245-1']);
  _gaq.push(['_setDomainName', 'xtribe.co']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
	
	</script>
</head>
<body>
	<div class="page">
		<header>
            
        </header>
		<section id="main">
            @RenderBody()
        </section>
		<footer>
        </footer>
	</div>
</body>
</html>

XTribe.Web/Views/Shared/_LogOnPartial.cshtml
@if( Request.IsAuthenticated )
{ @Html.ActionLink( "Log Off", "LogOff", "Account" ) 
}
else
{
	<fb:login-button perms="email,user_checkins" onlogin="afterFacebookConnect();" autologoutlink="false"></fb:login-button>
	<div id="fb-root" style="display: inline; margin-left: 20px;">
	</div>
}

XTribe.Web/Views/Shared/_loggedInLayout.cshtml
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="HandheldFriendly" content="True">
	<meta name="MobileOptimized" content="320">
	<meta name="viewport" content="width=device-width">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/content/imagesh/apple-touch-icon.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/content/imagesm/apple-touch-icon.png">
	<link rel="apple-touch-icon-precomposed" href="/content/imagesl/apple-touch-icon-precomposed.png">
	<link rel="shortcut icon" href="/content/imagesl/apple-touch-icon.png">
	<meta http-equiv="cleartype" content="on">
	<title>@ViewBag.Title</title>
	<link href='http://fonts.googleapis.com/css?family=Jockey+One' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="/content/style.css">
	<link rel="stylesheet" href="/Content/jquery-ui-1.8.20.custom.css" type="text/css"
		media="all" />
	@RenderSection( "CSS", false )
</head>
<body>
	<div id="header" class="navbar navbar-fixed-top container row">
		<div class="navbar-inner">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
				class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
			</a>
			<div class="nav-collapse collapse">
				<ul id="menu" class="nav">
					<li>@Html.ActionLink( "Home", "Index", "Snow" )</li>
					<li>@Html.ActionLink( "Wall", "Wall", "Profile" )</li>
					<li>@Html.ActionLink( "People", "People" )</li>
					<li>@Html.ActionLink( "Tracks", "Tracks" )</li>
				</ul>
				<ul class="secondary-nav nav">
					<li>@Html.ActionLink( "About", "About", "Snow" )</li>
					<li class="fb_button">@Html.Partial( "_LogOnPartial" )</li>
				</ul>
			</div>
		</div>
	</div>
	<div id="main" class="row container">
		@RenderBody()
	</div>
	<div id="footer" class="row navbar-inner navbar-fixed-bottom">
		<div class="container-fluid">
			<ul id="tribeMenu" class="nav">
				<li><a href="/surfing">
					<img src="/Content/Landing/thumb_wave.png" alt="Is the wild water your ball park? Check out the tidal-tribe." />
				</a></li>
				<li><a href="/mountain-biking">
					<img src="/Content/Landing/thumb_wheel.png" alt="Is the wild water your ball park? Check out the tidal-tribe." />
				</a></li>
				<li><a href="/snow">
					<img src="/Content/Landing/thumb_mountain.png" alt="Is the wild water your ball park? Check out the tidal-tribe." />
				</a></li>
			</ul>
		</div>
		<div id="title">
			<h1>
				snow-tribe</h1>
		</div>
	</div>
	<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
	<script>		window.jQuery || document.write('<script src="/Scripts/vendor/jquery-1.8.1.min.js"><\/script>')</script>
    <script src="@Url.Content( "~/Scripts/vendor/modernizr-2.6.1-respond-1.1.0.min.js" )" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/jquery.signalR-0.5.3.min.js")" type="text/javascript"></script>

	<script src="@Url.Content( "~/Scripts/helper.js" )" type="text/javascript"></script>
	<script src="@Url.Content( "~/Scripts/plugins.js" )" type="text/javascript"></script>
	<script src="@Url.Content( "~/Scripts/search.js" )" type="text/javascript"></script>
	<script language="javascript" type="text/javascript">

		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-32354245-1']);
		_gaq.push(['_setDomainName', 'xtribe.co']);
		_gaq.push(['_trackPageview']);

		(function () {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

		window.fbAsyncInit = function () {
			FB.init({ appId: '323177461089690',
				status: true, cookie: false, xfbml: true
			});
		};
		function afterFacebookConnect() {
			FB.getLoginStatus(function (response) {
				if (response.authResponse) {
					window.location = "../Account/FacebookLogin?token=" +
	                    response.authResponse.accessToken;
				} else {
					// user clicked Cancel
				}
			});
		};
		$(document).ready(function () {
			if (document.getElementById('fb-root') != undefined) {
				var e = document.createElement('script');
				e.type = 'text/javascript';
				e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
				e.async = true;
				document.getElementById('fb-root').appendChild(e);
			}
		});
	</script>
	@RenderSection( "JS", false )
</body>
</html>